#!/bin/bash
# rbk-lib.sh — shared functions for the rekordbox backup kit.
# Sourced by every rbk-*.sh script and by Install.command. Not meant to be run directly.
# Compatible with the bash 3.2 that ships with macOS.

RBK_VERSION="1.3.2"
RBK_TAG="${RBK_TAG:-rbk}"

# ---------------------------------------------------------------------------
# Locations on this Mac (everything local lives under RBK_HOME)
# ---------------------------------------------------------------------------
RBK_HOME="${RBK_HOME:-$HOME/Library/Application Support/rekordbox-backup}"
RBK_LOCAL_BIN="$RBK_HOME/bin"          # always on this Mac: the launchd launcher (rbk-launch.sh) — plus the scripts when installed locally
RBK_BIN="$RBK_LOCAL_BIN"               # where the scripts run from; INSTALL_DIR in config.sh can move this to the backup folder / any folder
DEFAULT_INSTALL_DIR="$RBK_LOCAL_BIN"
DEFAULT_APP_DIR="$HOME/Applications"
RBK_STATE="$RBK_HOME/state"
RBK_CONFIG="$RBK_HOME/config.sh"
RBK_LOG_DIR="${RBK_LOG_DIR:-$HOME/Library/Logs/rekordbox-backup}"
RBK_LOG="$RBK_LOG_DIR/rekordbox-backup.log"
RBK_LAUNCH_AGENTS="$HOME/Library/LaunchAgents"
RBK_LABEL_INTERVAL="com.rekordbox-backup-kit.interval"
RBK_LABEL_DAILY="com.rekordbox-backup-kit.daily"
# Jobs left behind by pre-release kits (any label matching *.rekordbox-backup.* other than the two above) are removed on install/uninstall
rbk_legacy_labels() {
    local p l
    for p in "$RBK_LAUNCH_AGENTS"/*.rekordbox-backup.*.plist; do
        [ -f "$p" ] || continue
        l=$(basename "$p" .plist)
        [ "$l" = "$RBK_LABEL_INTERVAL" ] || [ "$l" = "$RBK_LABEL_DAILY" ] || printf '%s\n' "$l"
    done
}
RBK_KIT_COPY="$RBK_HOME/kit"    # full copy of the kit (README, commands...) so Settings can re-seed a new backup folder
RBK_APP_DIR="$DEFAULT_APP_DIR"       # APP_DIR in config.sh can change this (~/Applications or /Applications)
RBK_APP_NAME="rekordbox Backup.app"

# What we protect — defaults for a standard rekordbox 6/7 install. Both can be changed in
# config.sh (LIBRARY_DIR / SETTINGS_DIR), e.g. when the database was moved to an external disk
# with rekordbox > Preferences > Advanced > Database management > Move Database.
DEFAULT_LIBRARY_DIR="$HOME/Library/Pioneer"
DEFAULT_SETTINGS_DIR="$HOME/Library/Application Support/Pioneer"
PIONEER_DIR="${PIONEER_DIR:-$DEFAULT_LIBRARY_DIR}"
APPSUPPORT_DIR="${APPSUPPORT_DIR:-$DEFAULT_SETTINGS_DIR}"

# Defaults — override in config.sh
KEEP_DAILY=14          # dated database snapshots
KEEP_MONTHLY=6         # first snapshot of each month, kept this many months
KEEP_MANUAL=10         # snapshots made with "Back up now"
KEEP_PRERESTORE=2      # local safety copies made before a restore
STALE_DAYS=3           # warn if no successful backup for this many days
NOTIFY_SUCCESS=1       # 1 = notification after every completed backup (auto + manual); 0 = manual/failures only

# Folders/files never worth backing up (regenerated by rekordbox)
RBK_EXCLUDE_DIRS="log Log logs Logs cache Cache caches Caches tmp temp"

# ---------------------------------------------------------------------------
# Platform helpers
# ---------------------------------------------------------------------------
rbk_is_mac() { [ "$(uname -s)" = "Darwin" ]; }

rbk_file_size()  { if rbk_is_mac; then stat -f %z -- "$1"; else stat -c %s -- "$1"; fi; }
rbk_file_mtime() { if rbk_is_mac; then stat -f %m -- "$1"; else stat -c %Y -- "$1"; fi; }
rbk_file_blocks(){ if rbk_is_mac; then stat -f %b -- "$1"; else stat -c %b -- "$1"; fi; }

rbk_sha256() { if command -v shasum >/dev/null 2>&1; then shasum -a 256 | cut -d' ' -f1; else sha256sum | cut -d' ' -f1; fi; }

rbk_now()      { date '+%Y-%m-%d %H:%M:%S'; }
rbk_now_id()   { date '+%Y-%m-%d_%H%M%S'; }
rbk_today()    { date '+%Y-%m-%d'; }
rbk_epoch()    { date '+%s'; }

rbk_human() {   # bytes -> human readable
    awk -v b="${1:-0}" 'BEGIN{ split("B KB MB GB TB",u," "); i=1; while (b>=1024 && i<5){b/=1024; i++}; printf (i==1?"%d %s":"%.1f %s"), b, u[i] }'
}

rbk_rsync_bin() {
    if [ -x /opt/homebrew/bin/rsync ]; then echo /opt/homebrew/bin/rsync
    elif [ -x /usr/local/bin/rsync ]; then echo /usr/local/bin/rsync
    else command -v rsync; fi
}

# ---------------------------------------------------------------------------
# Logging & notifications
# ---------------------------------------------------------------------------
rbk_log() {
    mkdir -p "$RBK_LOG_DIR" 2>/dev/null
    printf '%s [%s] %s\n' "$(rbk_now)" "$RBK_TAG" "$*" >> "$RBK_LOG" 2>/dev/null
    if [ -t 1 ] || [ "${RBK_VERBOSE:-0}" = "1" ]; then printf '%s\n' "$*"; fi
}
rbk_say()  { printf '%s\n' "$*"; }                     # always to the user
rbk_fail() { rbk_log "ERROR: $*"; rbk_notify "rekordbox Backup — problem" "$*"; }

rbk_as_escape() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }   # for AppleScript strings

rbk_notify() {  # title, message
    if [ -n "${RBK_TEST_NOTIFY_LOG:-}" ]; then printf '%s | %s\n' "$1" "$2" >> "$RBK_TEST_NOTIFY_LOG"; fi   # test hook
    rbk_is_mac || return 0
    command -v osascript >/dev/null 2>&1 || return 0
    local t m; t=$(rbk_as_escape "$1"); m=$(rbk_as_escape "$2")
    osascript -e "display notification \"$m\" with title \"$t\"" >/dev/null 2>&1 || true
}

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
rbk_load_config() {
    if [ ! -f "$RBK_CONFIG" ]; then
        rbk_say "Config not found: $RBK_CONFIG"
        rbk_say "Run Install.command first."
        return 1
    fi
    # shellcheck disable=SC1090
    . "$RBK_CONFIG"
    if [ -z "${BACKUP_DIR:-}" ]; then
        rbk_say "config.sh is incomplete (BACKUP_DIR missing). Re-run Install.command or open Settings in the app."
        return 1
    fi
    # folders (all four can be changed in the app > Settings...)
    LIBRARY_DIR="${LIBRARY_DIR:-$DEFAULT_LIBRARY_DIR}";   PIONEER_DIR="$LIBRARY_DIR"
    SETTINGS_DIR="${SETTINGS_DIR:-$DEFAULT_SETTINGS_DIR}"; APPSUPPORT_DIR="$SETTINGS_DIR"
    MUSIC_DIR="${MUSIC_DIR:-}"          # optional — only read by "Check music"
    DRIVE_ROOT="${DRIVE_ROOT:-}"        # optional — the cloud folder the backup folder lives in (for the "is it mounted" check)
    INSTALL_DIR="${INSTALL_DIR:-$DEFAULT_INSTALL_DIR}"; RBK_BIN="$INSTALL_DIR"   # where the scripts live (this Mac / backup folder / other)
    APP_DIR="${APP_DIR:-$DEFAULT_APP_DIR}";             RBK_APP_DIR="$APP_DIR"
    LATEST_DIR="$BACKUP_DIR/latest"
    HISTORY_DIR="$BACKUP_DIR/history"
    OFFICIAL_DIR="$BACKUP_DIR/official"
    DRIVE_LOG_DIR="$BACKUP_DIR/logs"
    mkdir -p "$RBK_STATE" "$RBK_LOG_DIR" 2>/dev/null
    return 0
}

# Best default cloud folder for an unattended install: the first detected cloud folder that
# contains a "Music" folder, else the first detected cloud folder (external disks are not defaults).
rbk_detect_drive_root() {
    local l p first=""
    while IFS=$'\t' read -r l p; do
        [ -n "$p" ] || continue
        case "$l" in "External disk"*) continue ;; esac
        [ -n "$first" ] || first="$p"
        [ -d "$p/Music" ] && { printf '%s\n' "$p"; return 0; }
    done < <(rbk_detect_destinations)
    [ -n "$first" ] && printf '%s\n' "$first"
}

# Is the backup destination reachable? (cloud app running / disk connected)
rbk_dest_available() {
    [ -d "$BACKUP_DIR" ] || return 1
    [ -z "${DRIVE_ROOT:-}" ] || [ -d "$DRIVE_ROOT" ]
}
rbk_drive_available() { rbk_dest_available; }   # old name, kept for the scripts

# Where the scripts are installed: "local" (this Mac), "backup" (the kit/ folder inside the backup folder) or "other"
rbk_realpath() { local p="${1%/}" par; if [ -d "$p" ]; then (cd "$p" && pwd -P); else par=$(dirname "$p"); if [ -d "$par" ]; then printf '%s/%s\n' "$(cd "$par" && pwd -P)" "$(basename "$p")"; else printf '%s\n' "$p"; fi; fi; }
rbk_install_kind() {
    local i; i=$(rbk_realpath "${INSTALL_DIR:-$DEFAULT_INSTALL_DIR}")
    if [ "$i" = "$(rbk_realpath "$RBK_LOCAL_BIN")" ]; then echo local
    elif [ -n "${BACKUP_DIR:-}" ] && [ "$i" = "$(rbk_realpath "$BACKUP_DIR/kit")" ]; then echo backup
    else echo other; fi
}
rbk_install_available() { [ -f "${INSTALL_DIR:-$DEFAULT_INSTALL_DIR}/rbk-backup.sh" ]; }
rbk_install_text() {   # one human line
    case "$(rbk_install_kind)" in
        local)  echo "on this Mac — $INSTALL_DIR" ;;
        backup) echo "inside the backup folder — $INSTALL_DIR (backups run only while it is available)" ;;
        *)      echo "$INSTALL_DIR (backups run only while it is available)" ;;
    esac
}

# Candidate backup destinations on this Mac, one per line:  label<TAB>path
# Any cloud service that shows a folder in Finder works (the wizard also offers "Other folder…");
# these are detected automatically: Google Drive, Dropbox, iCloud Drive, OneDrive, Box, Proton Drive,
# pCloud, MEGA, Nextcloud, Sync.com, plus writable external volumes.
rbk_detect_destinations() {
    local d sub pick n
    for d in "$HOME/Library/CloudStorage"/GoogleDrive-*; do
        [ -d "$d" ] || continue
        pick=""
        for sub in "$d"/*/; do            # prefer "My Drive" (localised names vary), skip shared drives
            sub="${sub%/}"; n="$(basename "$sub")"
            case "$n" in "My Drive") pick="$sub"; break;; esac
            [ -d "$sub/Music" ] && { pick="$sub"; break; }
            case "$n" in *[Ss]hared*|*condivis*|*partag*|*[Gg]eteilt*|*compartid*|.*) continue;; esac
            [ -n "$pick" ] || pick="$sub"
        done
        [ -n "$pick" ] && printf 'Google Drive (%s)\t%s\n' "${d##*GoogleDrive-}" "$pick"
    done
    for d in "$HOME/Google Drive"/*/ ; do [ -d "$d" ] && printf 'Google Drive\t%s\n' "${d%/}"; done 2>/dev/null
    for d in "$HOME/Library/CloudStorage"/Dropbox* "$HOME/Dropbox"; do [ -d "$d" ] && printf 'Dropbox\t%s\n' "$d"; done
    d="$HOME/Library/Mobile Documents/com~apple~CloudDocs"; [ -d "$d" ] && printf 'iCloud Drive\t%s\n' "$d"
    for d in "$HOME/Library/CloudStorage"/OneDrive*; do [ -d "$d" ] && printf 'OneDrive\t%s\n' "$d"; done
    for d in "$HOME/Library/CloudStorage"/Box* "$HOME/Box"; do [ -d "$d" ] && printf 'Box\t%s\n' "$d"; done
    for d in "$HOME/Library/CloudStorage"/ProtonDrive*; do [ -d "$d" ] && printf 'Proton Drive\t%s\n' "$d"; done
    [ -d "$HOME/pCloud Drive" ] && printf 'pCloud\t%s\n' "$HOME/pCloud Drive"
    [ -d "$HOME/MEGA" ] && printf 'MEGA\t%s\n' "$HOME/MEGA"
    [ -d "$HOME/Nextcloud" ] && printf 'Nextcloud\t%s\n' "$HOME/Nextcloud"
    [ -d "$HOME/Sync" ] && printf 'Sync.com\t%s\n' "$HOME/Sync"
    for d in /Volumes/*; do
        [ -d "$d" ] || continue
        [ "$(cd "$d" 2>/dev/null && pwd -P)" = "/" ] && continue        # the boot volume
        [ -w "$d" ] || continue
        printf 'External disk (%s)\t%s\n' "$(basename "$d")" "$d"
    done
    return 0
}

# Write config.sh from the current variables (keeps retention/notification settings)
rbk_write_config() {
    mkdir -p "$RBK_HOME"
    cat > "$RBK_CONFIG" <<CFG
# rekordbox backup kit — configuration  (written $(rbk_now); edit here or use the app > Settings...)
LIBRARY_DIR="${LIBRARY_DIR:-$DEFAULT_LIBRARY_DIR}"     # rekordbox library folder (contains rekordbox7/master.db or master.db)
SETTINGS_DIR="${SETTINGS_DIR:-$DEFAULT_SETTINGS_DIR}"  # rekordbox settings folder
BACKUP_DIR="${BACKUP_DIR:-}"                       # where backups go (any cloud folder, external disk, NAS...)
MUSIC_DIR="${MUSIC_DIR:-}"                         # optional: music folder — NEVER written to, only checked by "Check music"
DRIVE_ROOT="${DRIVE_ROOT:-}"                       # optional: cloud/disk root that must be mounted for backups to run
INSTALL_DIR="${INSTALL_DIR:-$DEFAULT_INSTALL_DIR}"  # where the scripts are installed: this Mac (default), the backup folder's kit/, or any folder
APP_DIR="${APP_DIR:-$DEFAULT_APP_DIR}"              # where "rekordbox Backup.app" is built (~/Applications or /Applications)
KEEP_DAILY=${KEEP_DAILY:-14}         # dated database snapshots to keep
KEEP_MONTHLY=${KEEP_MONTHLY:-6}      # first snapshot of each month, months to keep
KEEP_MANUAL=${KEEP_MANUAL:-10}       # "Back up now" snapshots to keep
KEEP_PRERESTORE=${KEEP_PRERESTORE:-2} # local safety copies kept after restores
STALE_DAYS=${STALE_DAYS:-3}          # warn when no backup succeeded for this many days
NOTIFY_SUCCESS=${NOTIFY_SUCCESS:-1}  # 1 = notification after every completed backup; 0 = only manual backups and problems
CFG
}

# ---------------------------------------------------------------------------
# rekordbox process control
# ---------------------------------------------------------------------------
rbk_rekordbox_running() {
    [ -n "${RBK_TEST_REKORDBOX_RUNNING:-}" ] && return 0    # test hook
    rbk_is_mac || return 1
    pgrep -x rekordbox >/dev/null 2>&1
}

rbk_quit_rekordbox() {   # graceful quit, waits up to 60 s
    rbk_is_mac || return 0
    osascript -e 'tell application "rekordbox" to quit' >/dev/null 2>&1 || true
    local i=0
    while [ $i -lt 60 ]; do
        rbk_rekordbox_running || return 0
        sleep 1; i=$((i+1))
    done
    return 1
}

rbk_stop_agent() {   # rekordboxAgent is a helper that can hold the database open
    rbk_is_mac || return 0
    pgrep -x rekordboxAgent >/dev/null 2>&1 && { pkill -x rekordboxAgent 2>/dev/null; sleep 2; }
    return 0
}

rbk_rekordbox_version() {
    local p
    for p in /Applications/rekordbox*/rekordbox.app/Contents/Info.plist /Applications/rekordbox.app/Contents/Info.plist; do
        [ -f "$p" ] || continue
        defaults read "${p%.plist}" CFBundleShortVersionString 2>/dev/null && return 0
    done
    echo "unknown"
}

# ---------------------------------------------------------------------------
# Locking (one backup/restore at a time)
# ---------------------------------------------------------------------------
rbk_lock() {
    local d="$RBK_STATE/lock.d"
    mkdir -p "$RBK_STATE"
    if mkdir "$d" 2>/dev/null; then echo $$ > "$d/pid"; return 0; fi
    local pid; pid=$(cat "$d/pid" 2>/dev/null)
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then return 1; fi
    rm -rf "$d"; mkdir "$d" 2>/dev/null && { echo $$ > "$d/pid"; return 0; }
    return 1
}
rbk_unlock() { rm -rf "$RBK_STATE/lock.d" 2>/dev/null; }

# ---------------------------------------------------------------------------
# Counting / fingerprints
# ---------------------------------------------------------------------------
# find(1) prune expression for excluded dir names, as separate args
rbk_prune_args() {
    local first=1 n
    printf '%s\n' "("
    for n in $RBK_EXCLUDE_DIRS; do
        [ $first = 1 ] || printf '%s\n' "-o"
        printf '%s\n' "-name" "$n"; first=0
    done
    printf '%s\n' ")" "-prune" "-o"
}

# All files worth backing up under a root (NUL separated)
rbk_list_files0() {
    local root="$1"; [ -d "$root" ] || return 0
    local -a pr; local line
    pr=(); while IFS= read -r line; do pr[${#pr[@]}]="$line"; done < <(rbk_prune_args)
    find "$root" "${pr[@]}" -type f ! -name .DS_Store ! -name '*.log' -print0
}

rbk_count_files() { local root="$1"; [ -d "$root" ] || { echo 0; return; }; rbk_list_files0 "$root" | tr '\0' '\n' | grep -c . ; }

rbk_sum_bytes() {
    local root="$1"; [ -d "$root" ] || { echo 0; return; }
    if rbk_is_mac; then rbk_list_files0 "$root" | xargs -0 stat -f %z 2>/dev/null | awk '{s+=$1} END{printf "%d", s}'
    else rbk_list_files0 "$root" | xargs -0 -r stat -c %s 2>/dev/null | awk '{s+=$1} END{printf "%d", s}'; fi
}

# Files that carry the database-level data (everything except the bulky analysis "share" trees)
rbk_list_db_files() {
    local root="$1"; [ -d "$root" ] || return 0
    local -a pr; local line
    pr=(); while IFS= read -r line; do pr[${#pr[@]}]="$line"; done < <(rbk_prune_args)
    find "$root" \( -name share -prune \) -o "${pr[@]}" -type f ! -name .DS_Store ! -name '*.log' -print0 \
      | while IFS= read -r -d '' f; do
            printf '%s\t%s\t%s\n' "${f#$root/}" "$(rbk_file_size "$f")" "$(rbk_file_mtime "$f")"
        done | sort
}

rbk_db_fingerprint() {
    { rbk_list_db_files "$PIONEER_DIR"; rbk_list_db_files "$APPSUPPORT_DIR"; } | rbk_sha256 | cut -c1-16
}

# Anything changed since the stamp file? (fast: stops at the first hit)
rbk_sources_changed_since() {
    local stamp="$1"; [ -f "$stamp" ] || return 0
    local -a pr; local line hit
    pr=(); while IFS= read -r line; do pr[${#pr[@]}]="$line"; done < <(rbk_prune_args)
    hit=$(find "$PIONEER_DIR" "$APPSUPPORT_DIR" "${pr[@]}" -type f ! -name .DS_Store ! -name '*.log' -newer "$stamp" -print 2>/dev/null | head -n 1)
    [ -n "$hit" ]
}

rbk_count_changed_since() {   # how many backed-up files are newer than the stamp
    local stamp="$1"; [ -f "$stamp" ] || { echo 0; return; }
    local -a pr; local line
    pr=(); while IFS= read -r line; do pr[${#pr[@]}]="$line"; done < <(rbk_prune_args)
    find "$PIONEER_DIR" "$APPSUPPORT_DIR" "${pr[@]}" -type f ! -name .DS_Store ! -name '*.log' -newer "$stamp" -print 2>/dev/null | grep -c .
}

rbk_find_master_db() {   # newest master.db under the Pioneer folder (rekordbox7 preferred)
    local f
    for f in "$PIONEER_DIR/rekordbox7/master.db" "$PIONEER_DIR/rekordbox/master.db"; do
        [ -f "$f" ] && { printf '%s\n' "$f"; return 0; }
    done
    find "$PIONEER_DIR" -maxdepth 3 -name master.db -print 2>/dev/null | head -n 1
}

# ---------------------------------------------------------------------------
# Retention
# ---------------------------------------------------------------------------
# Keep the newest N entries matching a prefix in a dir; delete the rest.
rbk_keep_newest() {   # dir prefix keep
    local dir="$1" prefix="$2" keep="$3" n=0 p
    [ -d "$dir" ] || return 0
    ls -1d "$dir"/"$prefix"* 2>/dev/null | sort -r | while IFS= read -r p; do
        n=$((n+1))
        if [ $n -gt "$keep" ]; then rbk_log "Retention: removing $(basename "$p")"; rm -rf "$p"; fi
    done
}

# Daily snapshots: keep newest KEEP_DAILY; of the older ones keep the first of each month for KEEP_MONTHLY months.
rbk_prune_history() {
    [ -d "$HISTORY_DIR" ] || return 0
    local all older n cut p month prev_month monthly=""
    all=$(ls -1d "$HISTORY_DIR"/daily_* 2>/dev/null | sort)
    [ -n "$all" ] || { rbk_keep_newest "$HISTORY_DIR" "manual_" "$KEEP_MANUAL"; return 0; }
    n=$(printf '%s\n' "$all" | grep -c .)
    cut=$((n - KEEP_DAILY))
    if [ $cut -gt 0 ]; then
        older=$(printf '%s\n' "$all" | head -n $cut)
        prev_month=""
        while IFS= read -r p; do
            [ -n "$p" ] || continue
            month=$(basename "$p" | cut -c7-13)   # daily_YYYY-MM
            if [ "$month" != "$prev_month" ]; then monthly="$monthly$p"$'\n'; prev_month="$month"
            else rbk_log "Retention: removing $(basename "$p")"; rm -rf "$p"; fi
        done <<< "$older"
        # keep only the newest KEEP_MONTHLY month-representatives
        n=$(printf '%s' "$monthly" | grep -c .)
        cut=$((n - KEEP_MONTHLY))
        if [ $cut -gt 0 ]; then
            printf '%s' "$monthly" | head -n $cut | while IFS= read -r p; do
                [ -n "$p" ] || continue
                rbk_log "Retention: removing $(basename "$p") (older than $KEEP_MONTHLY months)"; rm -rf "$p"
            done
        fi
    fi
    rbk_keep_newest "$HISTORY_DIR" "manual_" "$KEEP_MANUAL"
}

rbk_prune_prerestore() {   # safety copies live next to the folders they came from
    local sfx d
    for sfx in ".pre-restore_" ".undone-restore_"; do
        for d in "$PIONEER_DIR" "$APPSUPPORT_DIR"; do
            rbk_keep_newest "$(dirname "$d")" "$(basename "$d")$sfx" "$KEEP_PRERESTORE"
        done
    done
}


# ---------------------------------------------------------------------------
# Automatic-backup schedule state (Pause / Resume)
# ---------------------------------------------------------------------------
# "on"        both launchd jobs loaded
# "paused"    jobs unloaded + disabled by rbk-toggle.sh (persists across reboots)
# "off"       jobs not loaded for another reason (not installed / failed) — re-run Install.command
rbk_auto_state() {
    if ! rbk_is_mac; then   # test stand-in: a state file plays the role of launchd
        if [ -f "$RBK_STATE/paused-since" ]; then echo paused
        elif [ -f "$RBK_STATE/test-auto-loaded" ]; then echo on
        else echo off; fi
        return 0
    fi
    local loaded=1 L
    for L in "$RBK_LABEL_INTERVAL" "$RBK_LABEL_DAILY"; do
        launchctl print "gui/$(id -u)/$L" >/dev/null 2>&1 || loaded=0
    done
    if [ $loaded = 1 ]; then echo on
    elif [ -f "$RBK_STATE/paused-since" ]; then echo paused
    else echo off; fi
}

rbk_auto_state_text() {   # one human line for status/app
    local st; st=$(rbk_auto_state)
    case "$st" in
        on)     echo "ON — next check $(rbk_next_check_text)" ;;
        paused) echo "PAUSED since $(cat "$RBK_STATE/paused-since" 2>/dev/null || echo '?') — nothing runs until you press Resume" ;;
        *)      echo "OFF — schedule not loaded (re-run Install.command)" ;;
    esac
}

rbk_next_check_text() {   # estimate from the last automatic run (interval 1800 s)
    local last now left; last=$(rbk_state_get last-run-epoch); now=$(rbk_epoch)
    [ -n "$last" ] || { echo "within 30 min"; return; }
    left=$(( 1800 - (now - last) ))
    if [ $left -le 60 ]; then echo "in about a minute"; else echo "in ~$((left/60)) min"; fi
}

# ---------------------------------------------------------------------------
# State
# ---------------------------------------------------------------------------
rbk_state_get() { cat "$RBK_STATE/$1" 2>/dev/null; }
rbk_state_set() { mkdir -p "$RBK_STATE"; printf '%s\n' "$2" > "$RBK_STATE/$1"; }

rbk_last_success_epoch() { rbk_state_get last-success-epoch; }
rbk_age_text() {   # epoch -> "3 h ago"
    local e="$1" now d
    [ -n "$e" ] || { echo "never"; return; }
    now=$(rbk_epoch); d=$((now - e))
    if [ $d -lt 3600 ]; then echo "$((d/60)) min ago"
    elif [ $d -lt 172800 ]; then echo "$((d/3600)) h ago"
    else echo "$((d/86400)) days ago"; fi
}
